### ISSUE TITLE
Support server side rendering (SSR)

### ISSUE THREAD

**Issue by HollyPony** [punkave/apostrophe-headless#8]
There is a way to provide a native server side rendering through a `render` back method as a fallback for scrapbookers / google robots ?

I haven't read all the code but it's a common issue using SPA.

I think, this way, an agnostic "router" manager should be also provided.

**Comment by boutell** [comment]
Hi @HollyPony, this module provides a REST API to power native or browser-based apps such as React apps, as an addition to a CMS that, as you know, is already focused on server side rendering; 100% of the rest of Apostrophe is your fallback layer that renders pages. (:

Or to put it another way, when acting as a REST backend Apostrophe really doesn't know what the URLs for the public would even look like — that would be the responsibility of something like [React running and rendering content on the server](http://redux.js.org/docs/recipes/ServerRendering.html). Or some entirely different frontend framework. Apostrophe is just the REST provider in this scenario and it doesn't really know what you want to render.

I think there might be some middle ground here, but I'm taking this stance mostly to encourage you to articulate what that middle ground would be.

**Comment by HollyPony** [comment]
You right, it look like more than an adapter for SSR to manage routes as fallbacks. Great, we'll take a look ;)
